---
topdir: ~/.offlineimap-mozilla
delete:
    3:
        - Trash
        - Junk
    7:
        - Bugs Unsorted
        - Bugs Releases
        - Cron
        - Unsorted
        - tb-drivers
        - Bugs CC
        - Apuppet
        - Cron AWS
    30:
        - My Bugs
        - Bugs New
        - Release Drivers
