#!/bin/sh
#
#    battery: print the state of the battery
#
#    Copyright (C) 2009 Raphaël Pinson.
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Raphaël Pinson <raphink@ubuntu.com>
#             Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

present=$(cat /sys/class/power_supply/BAT0/present)
full=$(cat  /sys/class/power_supply/BAT0/energy_full)
rem=$(cat /sys/class/power_supply/BAT0/energy_now)
state=$(cat /sys/class/power_supply/BAT0/status)
if [ $rem -ge 0 ] && [ $full -gt 0 ]; then
    percent=$(((100*$rem)/$full))
    if [ "$percent" -lt 15 ]; then
        tmux_colour="#[fg=colour197]"
    elif [ "$percent" -lt 35 ]; then
        tmux_colour="#[fg=colour208]"
    else
        tmux_colour="#[fg=colour232]"
    fi

    case $state in
        charging|Charging|Unknown) sign="⌁ " ;;
        discharging|Discharging) sign="☔ " ;;
        charged|Unknown|Full) sign=" ⚛ "; percent="" ;;
        *) sign="$state" ;;
    esac
    [ -n "$percent" ] || return
    printf $tmux_colour; printf "Btr: %s" "$percent"; printf "%s" "$sign"
fi
