---
- name: apt repositories
  apt_repository: repo='{{item}}' state=present
  become: yes
  with_items:
    - "deb http://www.deb-multimedia.org stretch main non-free"
    - "deb https://apt.dockerproject.org/repo debian-stretch main"
    - "deb http://ftp.debian.org/debian/ testing main contrib non-free"
    - "deb http://ftp.debian.org/debian/ unstable main contrib non-free"
    - "deb-src http://ftp.debian.org/debian/ testing main contrib non-free"
    - "deb-src http://ftp.debian.org/debian/ unstable main contrib non-free"
    - "deb http://security.debian.org/ testing/updates main contrib non-free"
    - "deb-src http://security.debian.org/ testing/updates main contrib non-free"
    - "deb [arch=amd64] https://repo.skype.com/deb stable main"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb http://toolbelt.heroku.com/ubuntu ./"
    - "deb http://httpredir.debian.org/debian experimental main"
    - "deb http://download.opensuse.org/repositories/home:/Horst3180/Debian_8.0/ /"

- name: apt pinning preferences
  copy: dest=/etc/apt/preferences.d/pinning src=apt_pinning
  become: yes
