---
- name: dnsmasq packages
  become: yes
  apt: update_cache=yes cache_valid_time=3600 name={{item}}
  with_items:
    - dnsmasq-base

- name: remove dnsmasq conflicting packages
  become: yes
  apt: update_cache=yes cache_valid_time=3600 name={{item}} state=absent
  with_items:
    - dnsmasq

- name: network-manager enable dnsmasq
  lineinfile: dest=/etc/NetworkManager/NetworkManager.conf line="dns=dnsmasq" insertafter="^plugins="
  become: yes

- name: dnsmasq configs, cache
  copy: dest=/etc/NetworkManager/dnsmasq.d/cache.conf content="cache-size=1000\n"
  become: yes

- name: dnsmasq configs, ipv6
  copy: dest=/etc/NetworkManager/dnsmasq.d/ipv6_listen.conf content="listen-address=::1\n"
  become: yes

- name: dnsmasq configs, strict-order
  copy: dest=/etc/NetworkManager/dnsmasq.d/strict_order.conf content="strict-order\n"
  become: yes
