---
- name: install nerd-fonts - make temp dir
  file:
    path: "/tmp/nerd_fonts_setup"
    state: directory

- name: install nerd-fonts - download fonts
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/archive/v{{nerd_fonts_version}}.zip
      dest: /tmp/nerd_fonts_setup/fonts.zip
  register: fonts_download

- name: install nerd-fonts - unzip
  command: chdir=/tmp/nerd_fonts_setup unzip fonts.zip
  when: fonts_download|changed
  register: fonts_unpack

- name: install nerd-fonts - for reals
  command: ./install.sh chdir=/tmp/nerd_fonts_setup/nerd-fonts-{{nerd_fonts_version}}
  when: fonts_unpack|changed
