---
- name: packages
  become: yes
  apt: update_cache=yes cache_valid_time=3600 name={{item}}
  with_items:
    - zsh
    - tmux
    - tmuxinator
    - vim
    - vim-gtk  # For X11 clipboard awareness
    - i3
    - mc
    - apt-file
    - silversearcher-ag
    - openssh-server
    - network-manager-openvpn-gnome
    - unzip
    - zip
    - htop
    - xclip
    - git
    - libnotify-bin
    - mercurial
    - sudo
    - flashplugin-nonfree
    - docker.io
    - virtualbox
    - rofi
    - xbacklight
    - xinput
    - virtualenvwrapper
    - offlineimap
    - mutt
    - postfix
    - gnome-screensaver
    - chromium
    - slim
    - stardict
    - calibre
    - qt4-qtconfig
    - android-tools-fastboot
    - android-tools-adb
    - imapfilter
    - urlview
    - links
    - zim
    - secure-delete
    - s3cmd
    - gnome-tweak-tool
    - aptitude
    - dmz-cursor-theme
    - jwhois
    - gparted
    - vinagre
    - workrave
    - fonts-font-awesome
    - virtualbox-guest-additions-iso
    - compton
    - easytag
    - icedove
    - calendar-google-provider
    - enigmail
    - feh
    - redshift-gtk
    - pinentry-curses
    - deja-dup
    - tree
    - info
    - jq
    - scrot
    - lxappearance
    - blueman
    - notmuch
    - google-chrome-stable
    - mosh

- name: dev
  become: yes
  apt: update_cache=yes cache_valid_time=3600 name={{item}}
  with_items:
    - devscripts
    - autoconf2.13
    - quilt
    - pbuilder
    - libiw-dev
    - libevent-dev
    - libyaml-dev
    - libmysqlclient-dev
    - libssl-dev
    - libffi-dev
    - libxml2-dev # nikola
    - libxslt1-dev # nikola
    - libjpeg9-dev # nikola
    - rustc
    - cargo
    - golang
    - equivs
    - ubuntu-archive-keyring # to build ubuntu packages in pbuilder
    - debocker
    - puppet-lint
    - docker-compose
    - sqlite3
    - heroku-toolbelt


- name: python
  become: yes
  apt: update_cache=yes cache_valid_time=3600 name={{item}}
  with_items:
    - python-zope.interface
    - python-openssl
    - python-cryptography
    - python-setuptools
    - python-pytest-cov
    - python-stdeb
    - python-gnomekeyring
    - python-sh
    - python-tox
    - ipython-notebook
    - ipython3-notebook
    - python2.7
    - python2.7-dev
    - python3
    - python3-dev
    - python-notify2
    - python-flake8
    - python3-flake8
    - python-simplejson

- name: emacs
  become: yes
  apt: update_cache=yes cache_valid_time=3600 name={{item}}
  with_items:
    - emacs
    - org-mode-doc
    - emacs-goodies-el
