---
- name: packages
  apt: update_cache=yes cache_valid_time=3600 name={{item}}
  become: yes
  with_items:
    - slim
    - libnotify-bin
- name: Use intel_backlight
  copy: dest=/etc/X11/xorg.conf.d/50-backlight.conf src=50-backlight.conf
  become: yes

- name: Synpatics config
  copy: dest=/etc/X11/xorg.conf.d/50-synaptics.conf src=50-synaptics.conf
  become: yes
