---
# Mozilla setup
- hosts: all
  vars:
    mozilla_dir: "{{HOME}}/mozilla"

  tasks:
    - name: mozilla dir
      file: dest={{HOME}}/mozilla state=directory

    - name: buildbotcustom.git
      git: repo=https://github.com/mozilla/build-buildbotcustom.git dest={{HOME}}/mozilla/buildbotcustom.git

    - name: buildbotcustom.hg
      hg: repo=https://hg.mozilla.org/build/buildbotcustom dest={{HOME}}/mozilla/buildbotcustom.hg

    - name: buildbotcustom symlink
      file: dest={{HOME}}/mozilla/buildbotcustom src={{HOME}}/mozilla/buildbotcustom.git state=link

    - name: tools.git
      git: repo=https://github.com/mozilla/build-tools.git dest={{HOME}}/mozilla/tools.git

    - name: tools symlink
      file: dest={{HOME}}/mozilla/tools src={{HOME}}/mozilla/tools.git state=link

    - name: buildbot-configs.git
      git: repo=https://github.com/mozilla/build-buildbot-configs.git dest={{HOME}}/mozilla/buildbot-configs.git

    - name: buildbot-configs.hg
      hg: repo=https://hg.mozilla.org/build/buildbot-configs dest={{HOME}}/mozilla/buildbot-configs.hg

    - name: buildbot-configs symlink
      file: dest={{HOME}}/mozilla/buildbot-configs src={{HOME}}/mozilla/buildbot-configs.git state=link

    - name: puppet.git
      git: repo=https://github.com/mozilla/build-puppet.git dest={{HOME}}/mozilla/puppet.git

    - name: puppet.hg
      hg: repo=https://hg.mozilla.org/build/puppet dest={{HOME}}/mozilla/puppet.hg

    - name: puppet symlink
      file: dest={{HOME}}/mozilla/puppet src={{HOME}}/mozilla/puppet.git state=link

    - name: mozharness.hg
      hg: repo=https://hg.mozilla.org/build/mozharness dest={{HOME}}/mozilla/mozharness.hg
