---
- hosts: all
  name: manage the system!
  tasks:
      - name: apt pinning preferences
        copy: dest=/etc/apt/preferences.d/pinning src={{DOTFILES}}/apt_pinning

      - name: apt repositories
        apt_repository: repo='{{item}}' state=present
        with_items:
            - "deb http://ftp.debian.org/debian/ testing main contrib non-free"
            - "deb-src http://ftp.debian.org/debian/ testing main contrib non-free"
            - "deb http://security.debian.org/ testing/updates main contrib non-free"
            - "deb-src http://security.debian.org/ testing/updates main contrib non-free"
            - "deb http://ftp.debian.org/debian/ unstable main contrib non-free"
            - "deb-src http://ftp.debian.org/debian/ unstable main contrib non-free"

      - name: packages
        apt: update_cache=yes cache_valid_time=3600 name={{item}}
        with_items:
          - zsh
          - tmux
          - tmux
          - vim
          - vim-gtk  # For X11 clipboard awareness
          - i3
          - mc
          - apt-file
          - silversearcher-ag
          - openssh-server
          - network-manager-openvpn-gnome
          - unzip
          - zip
          - htop
          - xclip
          - git
          - mercurial
          - sudo
          - flashplugin-nonfree
          - docker.io
          - virtualbox
          - rofi
          - xbacklight
          - xinput
          - virtualenvwrapper
          - offlineimap
          - mutt-patched
          - postfix
          - gnome-screensaver
          - chromium
          - stardict
          - equivs
          - calibre
          - qt4-qtconfig
          - libiw-dev
          - android-tools-fastboot
          - android-tools-adb
          - imapfilter
          - urlview
          - links
          - devscripts
          - libmysqlclient-dev
          - libssl-dev
          - libffi-dev
          - zim
          - libxml2-dev # nikola
          - libxslt1-dev # nikola
          - libjpeg9-dev # nikola
          - secure-delete
          - s3cmd
          - libyaml-dev
          - gnome-tweak-tool
          - aptitude
          - dmz-cursor-theme
          - jwhois
          - libevent-dev
          - golang
          - gparted
          - vinagre
          - workrave
          - fonts-font-awesome
          - virtualbox-guest-additions-iso
          - rustc
          - cargo
          - compton
          - easytag

      - name: python
        apt: update_cache=yes cache_valid_time=3600 name={{item}}
        with_items:
          - python-zope.interface
          - python-openssl
          - python-cryptography
          - python-setuptools
          - python-pytest-cov
          - python-stdeb
          - python-gnomekeyring
          - python-sh
          - python-tox
          - ipython-notebook
          - ipython3-notebook
          - python2.7
          - python2.7-dev
          - python3.5
          - python3.5-dev
          - python3
          - python3-dev
          - python-notify2

      - name: emacs
        apt: update_cache=yes cache_valid_time=3600 name={{item}}
        with_items:
          - emacs
          - org-mode-doc
          - emacs-goodies-el
